### ISSUE TITLE
From a retard.

### ISSUE THREAD

**Issue by ghost** [HELLBOY017/kernel_oneplus_sm8250#1]
I saw what you wrote about me so I thought I would just be a nice guy and tell you this will never work. I know because I tested it. Teo has a rating of 19. QCOM has one of somewhere around 30 or above I can't remember this early in the morning. So Teo never gets used. Now let's say you decide to crank up that rating higher than QCOM. The phone doesn't boot. The three commits you have for this are pointless. Just a little nod from a retard whose kernel is cringe. Maybe now you'll trust me a little bit. You're always welcome to check the sysfs. But just like the other kernel dev that was talking bad to me. You'll come to the same conclusion. You're welcome.

**Comment by RDS-007** [comment]
> I saw what you wrote about me so I thought I would just be a nice guy and tell you this will never work. I know because I tested it. Teo has a rating of 19. QCOM has one of somewhere around 30 or above I can't remember this early in the morning. So Teo never gets used. Now let's say you decide to crank up that rating higher than QCOM. The phone doesn't boot. The three commits you have for this are pointless. Just a little nod from a retard whose kernel is cringe. Maybe now you'll trust me a little bit. You're always welcome to check the sysfs. But just like the other kernel dev that was talking bad to me. You'll come to the same conclusion. You're welcome.

Sir make kernel. We all eager to try it :)

**Comment by HELLBOY017** [comment]
> I saw what you wrote about me so I thought I would just be a nice guy and tell you this will never work. I know because I tested it. Teo has a rating of 19. QCOM has one of somewhere around 30 or above I can't remember this early in the morning. So Teo never gets used. Now let's say you decide to crank up that rating higher than QCOM. The phone doesn't boot. The three commits you have for this are pointless. Just a little nod from a retard whose kernel is cringe. Maybe now you'll trust me a little bit. You're always welcome to check the sysfs. But just like the other kernel dev that was talking bad to me. You'll come to the same conclusion. You're welcome.

![Screenshot_20230212-170645_MT_Manager](https://user-images.githubusercontent.com/76108696/218308679-4d316302-ff4b-4f70-9662-3a6104f56734.png)
Kek such retardness
